// ---------------------------------------------------------------------------
// THORNWOOD DEEP — dense forest technical descent
//
// Identity: trees, roots, moss, mist, progressive density, line choice.
// ---------------------------------------------------------------------------

import type { Zone } from './track';
import type { TrackDefinition, ScriptedFeature, TrackLandmark } from './trackDef';
import { ATMOS_FOREST } from './trackDef';

export const THORNWOOD_SECTIONS: Zone[] = [
  {
    name: '01 THORNWOOD GATE', sub: 'FOREST SWALLOWS YOU',
    t0: 0.000, t1: 0.09,
    dirt: 0x5c4a38, verge: 0x2f5a26, far: 0x1d3a19,
    width: 13, rough: 0.55, steep: 0.070, surface: 'dirt',
    treeDensity: 1.10, treeType: 'pine', rockDensity: 0.18,
    crowd: 0.0, fog: 1.25,
    features: ['kicker', 'roller'],
    props: ['log', 'fence'],
    twist: 0.90,
    setpiece: 'START GATE',
  },
  {
    name: '02 ROOT RUN', sub: 'CAN\'T SEE THE GROUND',
    t0: 0.09, t1: 0.22,
    dirt: 0x4a3828, verge: 0x26441e, far: 0x1a3016,
    width: 10.5, rough: 1.65, steep: 0.025, surface: 'mud',
    treeDensity: 1.85, treeType: 'pine', rockDensity: 0.15,
    crowd: 0.0, fog: 2.2,
    features: ['whoops', 'roller'],
    props: ['log', 'log', 'rock'],
    twist: 1.60,
    setpiece: 'PINE PLUNGE',
  },
  {
    name: '03 ANCIENT GROVE', sub: 'CATHEDRAL OF WOOD',
    t0: 0.22, t1: 0.32,
    dirt: 0x4e3c2c, verge: 0x2a4820, far: 0x1c3418,
    width: 11, rough: 1.10, steep: 0.020, surface: 'dirt',
    treeDensity: 1.70, treeType: 'pine', rockDensity: 0.20,
    crowd: 0.0, fog: 1.9,
    features: ['berm', 'roller', 'kicker'],
    props: ['log', 'fence', 'rock'],
    twist: 1.35,
    setpiece: 'PINE PLUNGE',
  },
  {
    name: '04 BIRCH CLEARING', sub: 'BRIEF OPEN SKY',
    t0: 0.32, t1: 0.42,
    dirt: 0x6a5840, verge: 0x5a7a38, far: 0x3a5a28,
    width: 14.5, rough: 0.55, steep: 0.015, surface: 'dirt',
    treeDensity: 0.50, treeType: 'broad', rockDensity: 0.10,
    crowd: 0.4, fog: 0.9,
    features: ['kicker', 'berm'],
    props: ['cone', 'bale'],
    twist: 0.80,
    setpiece: 'KICKER RIDGE',
  },
  {
    name: '05 MUDWALLS', sub: 'SOFT EDGES',
    t0: 0.42, t1: 0.54,
    dirt: 0x3e3024, verge: 0x3a4e2c, far: 0x2a3a1e,
    width: 13, rough: 0.90, steep: -0.010, surface: 'mud',
    treeDensity: 0.70, treeType: 'broad', rockDensity: 0.20,
    crowd: 0.3, fog: 1.5,
    features: ['berm', 'roller', 'kicker'],
    props: ['bale', 'puddle', 'fence'],
    twist: 1.0,
    secret: true,
    setpiece: 'MUDPIT MIRE',
  },
  {
    name: '06 ROOT TUNNEL', sub: 'UNDER THE GIANTS',
    t0: 0.54, t1: 0.64,
    dirt: 0x3a2c20, verge: 0x243a1c, far: 0x182c14,
    width: 10, rough: 1.40, steep: 0.035, surface: 'mud',
    treeDensity: 1.95, treeType: 'pine', rockDensity: 0.12,
    crowd: 0.0, fog: 2.4,
    features: ['whoops', 'roller'],
    props: ['log', 'log', 'water'],
    twist: 1.50,
    setpiece: 'PINE PLUNGE',
  },
  {
    name: '07 BONK ALLEY', sub: 'AMBUSH COUNTRY',
    t0: 0.64, t1: 0.76,
    dirt: 0x564434, verge: 0x305024, far: 0x22381a,
    width: 11, rough: 0.65, steep: 0.040, surface: 'dirt',
    treeDensity: 0.95, treeType: 'pine', rockDensity: 0.15,
    crowd: 0.5, fog: 1.15,
    features: ['roller', 'berm'],
    props: ['log', 'sign', 'barrel'],
    twist: 0.85,
    combat: true,
    setpiece: 'THE BONKYARD',
  },
  {
    name: '08 MIST RAVINE', sub: 'NO HORIZON',
    t0: 0.76, t1: 0.86,
    dirt: 0x484034, verge: 0x3a4a30, far: 0x2a3a24,
    width: 10.5, rough: 1.00, steep: 0.045, surface: 'dirt',
    treeDensity: 1.40, treeType: 'mixed', rockDensity: 0.35,
    crowd: 0.15, fog: 2.0,
    features: ['berm', 'whoops', 'kicker'],
    props: ['log', 'rock', 'fence'],
    twist: 1.25,
    dropSide: 1, dropDepth: 3.2,
    setpiece: 'PINE PLUNGE',
  },
  {
    name: '09 ROOT DROP', sub: 'STEEP & ROUGH',
    t0: 0.86, t1: 0.94,
    dirt: 0x4c3a2a, verge: 0x2c4e22, far: 0x1e3a18,
    width: 11.5, rough: 1.35, steep: 0.085, surface: 'mud',
    treeDensity: 0.75, treeType: 'pine', rockDensity: 0.25,
    crowd: 0.2, fog: 1.4,
    features: ['whoops', 'kicker', 'double'],
    props: ['log', 'rock'],
    twist: 1.05,
    setpiece: 'MUDPIT MIRE',
  },
  {
    name: '10 EMERGENCE', sub: 'LIGHT AT THE END',
    t0: 0.94, t1: 1.001,
    dirt: 0x5e4c3a, verge: 0x4a6a34, far: 0x3a5228,
    width: 15.5, rough: 0.40, steep: 0.055, surface: 'dirt',
    treeDensity: 0.28, treeType: 'mixed', rockDensity: 0.10,
    crowd: 1.8, fog: 0.75,
    features: ['kicker', 'table', 'berm'],
    props: ['cone', 'bale', 'sign'],
    twist: 0.35,
    setpiece: 'FINISH FURY',
  },
];

export const THORNWOOD_SETPIECES: ScriptedFeature[] = [
  { kind: 'kicker', at: 0.04, len: 14, h: 2.0, depth: 0 },
  { kind: 'whoops', at: 0.14, len: 26, h: 0.7, depth: 0 },
  { kind: 'double', at: 0.27, len: 22, h: 1.8, depth: 0.9 },
  { kind: 'kicker', at: 0.38, len: 16, h: 2.4, depth: 0 },
  { kind: 'berm', at: 0.48, len: 36, h: 1.6, depth: 0 },
  { kind: 'whoops', at: 0.58, len: 22, h: 0.6, depth: 0 },
  { kind: 'gap', at: 0.80, len: 36, h: 3.2, depth: 3.5 },
  { kind: 'kicker', at: 0.91, len: 18, h: 2.8, depth: 0 },
  { kind: 'kicker', at: 0.97, len: 16, h: 3.0, depth: 0 },
];

export const THORNWOOD_LANDMARKS: TrackLandmark[] = [
  { id: 'gate', kind: 'start_tower', at: 0.03, side: 1, label: 'Thornwood Gate' },
  { id: 'ancient', kind: 'ancient_tree', at: 0.26, side: -1, scale: 1.4, label: 'Ancient Tree' },
  { id: 'roots', kind: 'root_tunnel', at: 0.58, label: 'Root Tunnel' },
  { id: 'fallen', kind: 'fallen_giant', at: 0.18, label: 'Fallen Giant' },
  { id: 'mist', kind: 'mist_ravine', at: 0.80, side: 1, label: 'Misty Ravine' },
  { id: 'finish', kind: 'grandstand', at: 0.97, label: 'Emergence Finish' },
];

export const THORNWOOD: TrackDefinition = {
  id: 'thornwood',
  name: 'THORNWOOD DEEP',
  theme: 'forest',
  seed: 33911,
  length: 4900,
  difficulty: 4,
  sections: THORNWOOD_SECTIONS,
  setpieces: THORNWOOD_SETPIECES,
  landmarks: THORNWOOD_LANDMARKS,
  atmosphere: ATMOS_FOREST,
  startElevation: 920,
};
